spring.application.name=ecommerce-backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.database=${DB}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=dev
spring.batch.job.enabled=false
server.port=${PORT}


management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.export.prometheus.enabled=true
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true

# Show health details
management.endpoint.health.show-details=always

# Optional: Add custom metric tags
management.metrics.tags.application=ecommerce-backend