spring.application.name=ecommerce-backend
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ecommerce}
spring.datasource.username=${USERNAME:postgres}
spring.datasource.password=${PASS:password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.database=${DB:ecommerce}

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=dev
spring.batch.job.enabled=false
server.port=${PORT:8081}

spring.thymeleaf.check-template-location=false

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.export.prometheus.enabled=true
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true

# Show health details
management.endpoint.health.show-details=always

# Optional: Add custom metric tags
management.metrics.tags.application=ecommerce-backend

#spring.jpa.properties.hibernate.format_sql=true

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Secret key must be a Base64 encoded string of at least 256 bits (32 bytes)
app.jwt.secret=${TOKEN:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
# Token validity duration in milliseconds (e.g., 24 hours)
app.jwt.expiration=${EXPIRY:86400000}
